const fs = require('fs');
const path = require('path');
const vectorStore = require('../services/vectorStore.service');
const embeddingService = require('../services/embedding.service');

/**
 * INGESTION PIPELINE:
 * 1. Read Chunks: Load the token-aware chunks generated by chunker.js.
 * 2. Generate Embeddings: For each chunk, call the Gemini Embedding API.
 * 3. Store in Vectra: Save the vector and metadata into the local Vectra index.
 * 
 * This pipeline is explicit and modular, ensuring full transparency in the RAG workflow.
 */

async function ingest() {
    try {
        console.log('--- Starting Ingestion Pipeline ---');

        // Ensure index is ready
        await vectorStore.initialize();

        // Load chunks
        const chunksPath = path.join(__dirname, 'yoga_chunks.json');
        const chunks = JSON.parse(fs.readFileSync(chunksPath, 'utf8'));

        console.log(`Loading ${chunks.length} chunks from ${chunksPath}...`);

        for (let i = 0; i < chunks.length; i++) {
            const chunk = chunks[i];
            console.log(`[${i + 1}/${chunks.length}] Embedding chunk: ${chunk.title} (${chunk.chunk_id})`);

            try {
                const embedding = await embeddingService.generateEmbedding(chunk.content);

                await vectorStore.addItem(embedding, {
                    chunk_id: chunk.chunk_id,
                    article_id: chunk.article_id,
                    title: chunk.title,
                    category: chunk.category,
                    source_reference: chunk.source_reference,
                    source_link: chunk.source_link,
                    content: chunk.content // Storing content in metadata for easy retrieval
                });
            } catch (err) {
                console.error(`Failed to ingest chunk ${chunk.chunk_id}:`, err.message);
                // Continue with next chunk in case of single failure
            }
        }

        console.log('--- Ingestion Complete! ---');
        console.log('Vector index is now ready for retrieval.');

    } catch (error) {
        console.error('Ingestion failed:', error);
    }
}

// Check if running directly
if (require.main === module) {
    ingest();
}

module.exports = ingest;
